# An example of a scan service.
# This can be used for testing but a semantically meaningful
# one should be created to be built upon.
std_msgs/Float64MultiArray pose
float32 angle
---
std_msgs/Float64MultiArray nextpose
bool success